Rightpoint/BonMot

Example/Tests/BONTextAlignmentTestCase.m
Pod/Classes/BONChain.h
Pod/Classes/BONChain.m
Pod/Classes/BONText.h
Pod/Classes/BONText.m
README.md

This commit adds support for the lineSpacing NSParagraphStyle property. The paragraph style unit test has also been updated, along with the README to reflect the new supported property.

Add support for the lineSpacing paragraph style

---

Example/Tests/BONTextAlignmentTestCase.m
Pod/Classes/BONChain.h
Pod/Classes/BONChain.m
Pod/Classes/BONText.h
Pod/Classes/BONText.m
README.md

This commit adds several more attributes from the NSParagraphStyle properties, including the firstLineHeadIndent, headIndent, tailIndent, maximumLineHeight, minimumLineHeight, paragraphSpacing, and paragraphSpacingBefore properties. Unit tests have also been added to test these new properties.

Add more paragraph style attributes

---

.travis.yml
Example/BonMot/Cells/AbstractCell.m
Example/BonMot/Cells/BaselineCapHeightCell.m
Example/BonMot/Cells/BaselineOffsetCell.m
Example/BonMot/Cells/ColorCell.m
Example/BonMot/Cells/ConcatenationCell.m
Example/BonMot/Cells/FigureStyleCell.m
Example/BonMot/Cells/IndentationCell.m
Example/BonMot/Cells/InlineImagesCell.m
Example/BonMot/Cells/LineHeightCell.m
Example/BonMot/Cells/ProgrammaticBaselineCapHeightCell.m
Example/BonMot/Cells/SpecialCharactersCell.m
Example/BonMot/Cells/TrackingCell.m
Example/BonMot/DashedHairlineView.m
Example/BonMot/NSDictionary+BONEquality.h
Example/BonMot/NSDictionary+BONEquality.m
Example/BonMot/RootViewController.m
Example/Tests/BONChainableTestCase.m
Example/Tests/BONDictionaryEqualityTestCase.m
Example/Tests/BONIndentSpacerTestCase.m
Example/Tests/BONPropertyClobberingTestCase.m
Example/Tests/BONTextAlignmentConstraintTestCase.m
Example/Tests/BONTextAlignmentTestCase.m
Example/Tests/BONTrackingTestCase.m
Pod/Classes/BONText.m
Pod/Classes/BONTextAlignmentConstraint.m
Pod/Classes/UIImage+BonMotUtilities.m
README.md

@nbonatsakis @ateliercw @arrouse I don't know if anyone still cares about the Objective-C style guide, but this defnitely goes against it in the interest of cleaning up these warnings without just disabling the warnings in the project. This is so that people can use this in their projects without having to inhibit warnings from BonMot.

Fix Xcode 7.3 warnings about float/double precision

---

Example/Tests/BONTextAlignmentTestCase.m
Pod/Classes/BONChain.h
Pod/Classes/BONChain.m
Pod/Classes/BONText.h
Pod/Classes/BONText.m
README.md

For https://github.com/Raizlabs/BonMot/issues/111

add support for line break mode

---

README.md

Adds Swift equivalents for Readme code samples and puts Objective C versions in disclosable sections.
fixes #152

Feature/connorneville/Swift Code Samples

---

Example/BonMot-Example-iOS/DemoStrings.swift
Sources/AttributedStringStylePart.swift
Sources/NSAttributedString+BonMot.swift
Sources/XMLBuilder.swift
Tests/AttributedStringStyleTests.swift
Tests/Compatibility.swift
Tests/NSAttributedStringDebugTests.swift

Hey @ZevEisenberg -- I fixed the bug with debugRepresentation. This should resolve #146 and #197. The one thing that isn't ideal is the generated XML for unassigned unicode characters isn't imported back into the unassigned unicode character.  We could add support for this by having Special have associated values but it would be a good chunk of code churn for a feature I don't think anyone will ever want.

[4.0] Fix debugRepresentation

---

Sources/XMLBuilder.swift
Tests/XMLTagStyleBuilderTests.swift

As discussed in slack, this allows for use cases such as follows to support custom styles based on the parent style:
```swift
func style(forElement name: String, attributes: [String: String], currentStyle: StringStyle) -> StringStyle? {
let currentFont = currentStyle.font ?? baseFont
switch name.lowercased() {
case "i":
fallthrough
case "em":
guard currentFont.fontName != FontName.verlagBold.stringValue else {
return StringStyle.style(Styles.font(.verlagBoldItalic, size: currentFont.pointSize))
}
return StringStyle.style(Styles.font(.verlagBookItalic, size: currentFont.pointSize))
case "b":
fallthrough
case "strong":
guard currentFont.fontName != FontName.verlagBookItalic.stringValue else {
return StringStyle.style(Styles.font(.verlagBoldItalic, size: currentFont.pointSize))
}
return …
```

Add currentStyle to XMLStyler protocol's style function.

---

Sources/Composable.swift
Sources/StylePart.swift
Tests/AttributedStringStyleTests.swift

Based on conversation here: https://github.com/Raizlabs/BonMot/pull/228
I ended up still having to implement a `[T]` version `StringStyle(_:StylePart...)` in order to be able to create `styled(with:overrideParts:)`, but let me know if there is another way to do this I'm missing.

Adds `.styled(StringStyle)` part and `styled(with:overrideParts:)`

---

Example-iOS/StyleViewController.swift
Sources/UIKit/AdaptableTextContainer.swift
Sources/UIKit/AdaptiveStyleTransformation.swift
Sources/UIKit/NSAttributedString+Adaptive.swift
Sources/UIKit/StyleableUIElement.swift
Tests/AdaptiveStyleTests.swift

248 rename adapt(to:) to adapted(to:)

---

BonMot.xcodeproj/project.pbxproj
Example-iOS/Resources/Main.storyboard
Example-iOS/StyleViewController.swift
Sources/Compatibility.swift
Sources/Composable.swift
Sources/NSAttributedString+BonMot.swift
Sources/StringStyle+Part.swift
Sources/UIKit/AdaptableTextContainer.swift
Sources/UIKit/StyleableUIElement.swift
Sources/UIKit/UIKit+AdaptableTextContainerSupport.swift
Tests/Compatibility+Tests.swift
Tests/Compatibility.swift

Closes #252
This supersedes https://github.com/Raizlabs/BonMot/pull/253

252 Target Action

---

.gitignore
BonMot.podspec
Example-iOS/DemoStrings.swift
Sources/Image+Tinting.swift
Tests/ImageTintingTests.swift

The demo strings in the iOS Examples app are currently not accessible.
Specifically:
- The XML example has a decorative image that is visible to the accessibility system and shouldn’t be.
- The Composition example has a content image without alternative text.
- The Images & Special characters example has content images without alternative text.
Furthermore, there is a bug in the `tintedImage(color:)` method in the `BONImage` extension that loses the accessibility label on the original image.
This pull request:
1. Fixes the `tintedImage(color:)` method in the `BONImage` extension so that the resulting tinted image has the same accessibility label as the original image.
2. Adds accessibility support to the images in the iOS Example app.
3. (Minor) Adds the .idea folder added to projects by …

Accessibility

---

.swiftlint.yml
BonMot.xcodeproj/project.pbxproj
Sources/Compatibility.swift
Sources/StringStyle+Part.swift
Sources/StringStyle.swift
Sources/Transform.swift
Sources/XMLBuilder.swift
Tests/Compatibility+Tests.swift
Tests/TransformTests.swift

String transforms

---

circle.yml

Force uninstallation of all `carthage` formulae from `homebrew`.
Avoid second (unnecessary) update, and force installation of `carthage` [bottle (binary package)](https://github.com/Homebrew/brew/blob/master/docs/Bottles.md) from `homebrew`.

Resume testing Carthage support, force bottle installation.

---

Sources/Composable.swift
Sources/MutableCopying.swift
Sources/StringStyle+Part.swift
Tests/AttributedStringStyleTests.swift

This PR contains a currently-failing test, demonstrating what I believe to be broken behavior. I wanted to run it by @KingOfBrian and others before taking the time to fix it.

Overriding styles on attributed strings

---

Sources/Tracking.swift
Tests/AccessTests.swift

Currently kerning(forFont: ) method in Tracking enum has an internal attribute. It would be good if it will be public

Transform 'kerning(forFont: )' method to public

---

Sources/Composable.swift
Tests/ComposableTests.swift

The current implementation of `removeKerningFromLastCharacter` and `restoreKerningOnLastCharacter` start from the assumption that the last character range always has length 1. This however is not true for more complex characters, such as emojis.
The consequence of this was a bug in which applying a style to a string that ended with an emoji, while keeping the flag `stripTrailingKerning` to its default value of `true`, would result in the emoji not being shown at all.

Consider emoji when removing kerning from last character

---

Example-iOS/StyleViewController.swift
Sources/Compatibility.swift

This was never supposed to be public. It’s _techinically_ a breaking change for anyone depending on this behavior, but since updating BonMot requires a recompile anyway, I’m fine with just shipping this as a bug fix.

Stop exporting table view compatibility alias

---

Sources/UIKit/AdaptableTextContainer.swift
Sources/UIKit/AdaptiveStyle.swift
Sources/UIKit/AdaptiveStyleTransformation.swift
Sources/UIKit/EmbeddedTransformation.swift
Sources/UIKit/NSAttributedString+Adaptive.swift
Sources/UIKit/StyleableUIElement.swift
Sources/UIKit/Tab+Adaptive.swift
Sources/UIKit/TextAlignmentConstraint.swift
Sources/UIKit/Tracking+Adaptive.swift
Sources/UIKit/UIKit+AdaptableTextContainerSupport.swift
Sources/UIKit/UIKit+Helpers.swift

Do not compile UIKit code for watchOS

---

BonMot.podspec
Sources/StringStyle+Part.swift

Follow-up to #381 because GitHub won’t let me reopen it. Fixes #345.
Simplifies the `switch` statement in `StringStyle.update(part:)` using the improved interaction between switch and #if in Swift 4.1+. This requires removing Swift 4.0 from the supported versions. I think it’s better not to add new support for Swift 4.1, so that would make the minimum version Swift 4.2.

Simplify StringStyle.update(part:) switch statement

---

Example-iOS/DemoStrings.swift
Example-iOS/StyleViewController.swift
Sources/Composable.swift
Sources/FontFeatures.swift
Sources/Tab.swift
Sources/UIKit/AdaptableTextContainer.swift
Sources/UIKit/AdaptiveStyle.swift
Sources/UIKit/AttributedStringTransformation.swift
Sources/UIKit/NSAttributedString+Adaptive.swift
Sources/UIKit/StyleableUIElement.swift
Sources/XMLBuilder.swift
Tests/AdaptiveStyleTests.swift
Tests/AssertHelpers.swift
Tests/AttributedStringStyleTests.swift
Tests/ComposableTests.swift
Tests/NSAttributedStringDebugTests.swift
Tests/TransformTests.swift
Tests/UIKitBonMotTests.swift
Tests/XMLTagStyleBuilderTests.swift

The only interesting thing (and calling it _interesting_ is probably a stretch) is the commit that fixes a typo in public API by deprecating and renaming it. Please let me know if you think I've done it in a good way, and whether it constitutes a breaking change. (If the latter, we might as well just rename it and skip the deprecation.) It's a tricky case because the renamed parameter has a defaulted value, so consumers may not even be aware that there was a typo.

Test cleanup and typo fixes

---

Sources/NSAttributedString+BonMot.swift
Sources/Special.swift
Sources/XMLBuilder.swift
Tests/NSAttributedStringDebugTests.swift

For working project, I need to build this pod as binary framework. To avoid rebuild it with every new xcode, we build them with `BUILD_LIBRARY_FOR_DISTRIBUTION=YES`.
In this mode, swift generate swiftinterface file, which is crucial for module stability
Unfortunately it has bug, which make swiftinterface invalid for BonMot specifically.
Here is link for swift bug: https://bugs.swift.org/browse/SR-14355
Looks like it just skip string literals, because they are not needed,  and do not check that `RawValue` type is not `String`.
I see no other way, rather than change raw type to String. In this way swiftinterface can be compiled.
Additionally I added `CaseIterable` and still keep `all ` for backward compatibility.
I would appreciate if you take my changes and create new release, so I would …

Fix enum for module stability

---

Sources/UIKit/UIKit+AdaptableTextContainerSupport.swift

Fixed UIView extension method notifyContainedAdaptiveContentSizeContainers() by adding the ability to specify the trait collection and supplying one when updating a view controllers views and subviews when they aren't in the view hierarchy yet.
Fixes #399

Fixes notifyContainedAdaptiveContentSizeContainers()

---

Sources/XMLBuilder.swift
Tests/AttributedStringStyleTests.swift

Hello and thank you for this fine library!
I propose addition of several `XMLStyleRule`s to dynamically generate and apply styles, enter- and exit-insertions of elements.
With these changes, you can use them like this:
```swift
// We want to style an xml that contains tags with some important attributes
var quoteAuthorStack = [String]()
let attributedString = try NSAttributedString.composed(
ofXML: rawXml,
rules: [
.style("quote", quoteStyle),
// We want to insert an image with a beautiful quote before the actual quote text.
// Also we have an author's name in "author" attribute and we want 
// to append this name after the quote text.
.enterBlock(element: "quote") { attributes in
// Saving author's name for later use
quoteAuthorStack.append(attributes["author"]!)
// "author" handling was …
```

New XMLStyleRule variants for dynamic styling

---

BonMot.podspec
Sources/UIKit/AdaptableTextContainer.swift
Tests/UIKitBonMotTests.swift

Fixes UISegmentedControl extension crash and improves efficiency

---

Sources/Composable.swift
Tests/ComposableTests.swift

[] can be removed when using the composed method.
Overloading methods for optional use.

composed removed []
