Rightpoint/BonMot

- Example/BonMot.xcodeproj/project.pbxproj
- Example/BonMot/NSDictionary+BONEquality.h
- Example/BonMot/NSDictionary+BONEquality.m
- Example/Tests/BONBaseTestCase.h
- Example/Tests/BONBaseTestCase.m
- Example/Tests/BONDictionaryEqualityTestCase.m
- Example/Tests/BONTextConfigurationTestCase.m
- Pod/Classes/BONTextConfiguration.m
> Negative tracking

- Example/BonMot.xcodeproj/project.pbxproj
- Example/BonMot/Cells/BaselineCapHeightCell.m
- Example/BonMot/Cells/ProgrammaticBaselineCapHeightCell.h
- Example/BonMot/Cells/ProgrammaticBaselineCapHeightCell.m
- Example/BonMot/Cells/ProgrammaticBaselineCapHeightCell.xib
- Example/BonMot/Cells/SpecialCharactersCell.m
- Example/BonMot/NSDictionary+BONEquality.h
- Example/BonMot/NSDictionary+BONEquality.m
- Example/BonMot/RootViewController.m
- Example/Tests/BONBaseTestCase.h
- Example/Tests/BONDictionaryEqualityTestCase.m
- Example/Tests/BONTextAlignmentConstraintTestCase.m
- Pod/Classes/BONTextAlignmentConstraint.m
> make text alignment constraint usable in code

- Pod/Classes/BONSpecial.h
- Pod/Classes/BONSpecial.m
- scripts/BONSpecialGenerator.swift
- Updates script to run in xcode 7.0 GM
- Added paragraphSeparator to the BONSpecial list
> BONSpecial Updates

- Example/Tests/BONBaseTestCase.h
- Example/Tests/BONIndentSpacerTestCase.m
- Pod/Classes/BONChain.m
> Indent Spacer should be allowed to be 0

- .travis.yml
- Example/BonMot.xcodeproj/project.pbxproj
- Example/Tests/BONUnderlineAndStrikethroughTestCase.m
- Pod/Classes/BONChain.h
- Pod/Classes/BONChain.m
- Pod/Classes/BONText.h
- Pod/Classes/BONText.m
- README.md
This is a more complete version of #98, which it replaces. Thanks to @lifely for the initial work on underlining!
> Fixes #14 Underlining and #15 Strikethrough.

- Pod/BonMot.h
Compilation on Non case folded filesystems will now work.
> Compilation on Non case folded filesystems will now work.

- scripts/BONSpecial.h template.txt
- scripts/BONSpecial.m template.txt
Use BonMot in place of Pods / Correct syntax for ASSUME_NONNULL
> Fix BonSpecial Templates 

- Example/BonMot/Cells/ColorCell.m
- Example/BonMot/Cells/IndentationCell.m
- Example/BonMot/Cells/SpecialCharactersCell.m
- Example/Tests/BONIndentSpacerTestCase.m
- Example/Tests/BONTextableTestCase.m
- Example/Tests/BONTrackingTestCase.m
- Example/Tests/BONUnderlineAndStrikethroughTestCase.m
- Pod/Classes/BONChain.h
- Pod/Classes/BONChain.m
- Pod/Classes/BONText.h
- Pod/Classes/BONText.m
- README.md
> 135 rename -textColor to -color

- Example/Tests/BONChainEmptyTestCase.m
- Example/Tests/BONUIKitUtilitiesTestCase.m
- Pod/Classes/BONText.m
- Pod/UIKit/Classes/UILabel+BonMotUtilities.m
- Pod/UIKit/Classes/UITextField+BonMotUtilities.m
- Pod/UIKit/Classes/UITextView+BonMotUtilities.m
> Make UIKit extensions less confusing

- Example/Podfile.lock
- Example/Pods/Local Podspecs/BonMot.podspec.json
- Example/Pods/Manifest.lock
- Example/Pods/Pods.xcodeproj/xcshareddata/xcschemes/BonMot.xcscheme
- Example/Pods/Target Support Files/BonMot/Info.plist
- Example/Tests/BONUIKitUtilitiesTestCase.m
- Gemfile
- Gemfile.lock
- Pod/UIKit/Classes/UILabel+BonMotUtilities.h
- Pod/UIKit/Classes/UITextField+BonMotUtilities.h
- Pod/UIKit/Classes/UITextView+BonMotUtilities.h
> Add nullability annotations to UIKit utilities

- .travis.yml
- Example/Tests/BONBaseTestCase.h
- Example/Tests/BONTagTestCase.m
- Pod/Classes/BONTag.m
> Fix shared chain ranges bug

- Pod/Classes/BONChain.h
- Pod/Classes/BONChain.m
- Pod/Classes/BONText.h
- Pod/Classes/BONText.m
- README.md
> Add support for hyphenationFactor

- Pod/Classes/BONText.m
Make a comment consistent with the code.
> Head Indent -> Tail Indent

- README.md
@nevillco would you mind having a look at this?
> Add Swift Sections to ReadMe

- Pod/Classes/BONChain.m
- Pod/Classes/BONSpecial.h
- Pod/Classes/BONSpecial.m
- Pod/Classes/BONText.h
- Pod/Classes/BONText.m
- scripts/BONSpecialGenerator.swift
> Left-to-right Debug Strings

- Example/BonMot-Example-iOS/DemoStrings.swift
- Sources/AttributedStringStyle.swift
- Sources/AttributedStringStylePart.swift
- Sources/Compatibility.swift
- Sources/UIKit/TagStyles+IBInspectable.swift
- Sources/XMLBuilder.swift
- Tests/AttributedStringStyleTests.swift
It was all @KingOfBrian's idea.
> Naming things

- BonMot.xcodeproj/project.pbxproj
- Fixes carthage support bug if you are not up to date. 
- The language could be tweaked
> Swiftlint Incompatiblity Warning

- README.md
> BonMot 3 to 4 migration guide.

- README.md
> 224 differentiate throwing and non throwing parsers

- Example-iOS/DemoStrings.swift
- Example-iOS/Resources/Main.storyboard
- Example-iOS/StyleViewController.swift
Closes #238. Thanks to @msluetz and Sandy Machado for design feedback.
> 238 OpenType example

- README.md
- circle.yml
Thanks to @ateliercw for the wonderful hack
> Speed up linting

- README.md
Use blueStyle instead of redStyle in README.md
> Fix misspell

- scripts/iOS.sh
- scripts/tvOS.sh
- scripts/watchOS.sh
This [used to be broken](https://discuss.circleci.com/t/multiple-ios-simulators-available-for-single-os-device-configurations/7854), but it's [fixed now](https://twitter.com/dantoml/status/819984869300334592).
> Semantically specify simulators for tests

- BonMot.xcodeproj/project.pbxproj
Fixes #240
Question: is it possible to make Xcode auto-select a team? Or must we require users to select a team before building on device?
> Enable building example app on device

- Example-iOS/DemoStrings.swift
- Example-iOS/Resources/Main.storyboard
- Example-iOS/StyleViewController.swift
- Sources/StringStyle+Part.swift
- Sources/StringStyle.swift
- Tests/AttributedStringStyleTests.swift
- Tests/ComposableTests.swift
- Tests/Helpers.swift
> Speech Attributes

- Sources/Compatibility.swift
- Sources/StringStyle+Part.swift
- Sources/StringStyle.swift
- Tests/AttributedStringStyleTests.swift
- Tests/ComposableTests.swift
- Tests/Helpers.swift
- Tests/XMLTagStyleBuilderTests.swift
> Change outdated “NSURL” to modern “URL.”

- BonMot.xcodeproj/project.pbxproj
- Sources/AccessibilityHeadingLevel.swift
- Sources/StringStyle+Part.swift
- Sources/StringStyle.swift
- Tests/AttributedStringStyleTests.swift
- Tests/ComposableTests.swift
- Tests/Helpers.swift
> New accessibility attributes

- BonMot.xcodeproj/project.pbxproj
- Sources/Composable.swift
- Sources/Tab.swift
- Tests/AccessTests.swift
- Tests/AttributedStringStyleTests.swift
- Tests/NSAttributedStringDebugTests.swift
- Tests/TransformTests.swift
> Remove NSAttributedStringKey.kern from last character of styled strings

- .swiftlint.yml
- BonMot.xcodeproj/project.pbxproj
- Example-iOS/DemoStrings.swift
- Example-iOS/StyleViewController.swift
- Sources/Emphasis.swift
- Sources/Platform.swift
- Sources/StringStyle+Part.swift
- Sources/StringStyle.swift
- Tests/EmphasisTests.swift
Fixes #303.
Would love feedback on naming and API in general.
~add example to readme probably?~ decided not to; it's a nice detail that works when you want it, but no need to call it out explicitly, I think.
> Nested emphases

- Sources/Composable.swift
- Tests/ComposableTests.swift
> Join sequence of composable into attribute string

- .circleci/config.yml
- README.md
Wanted to land these separate from #340
> Small readme updates

- .circleci/config.yml
- .swiftlint.yml
- BonMot.xcodeproj/project.pbxproj
- Example-iOS/AppDelegate.swift
- Example-iOS/DemoStrings.swift
- Example-iOS/StyleViewController.swift
- Sources/ContextualAlternates.swift
- Sources/FontFeatures.swift
- Sources/FontInspector.swift
- Sources/StylisticAlternates.swift
- Tests/AdaptiveStyleTests.swift
- Tests/AssertHelpers.swift
- Tests/AttributedStringStyleTests.swift
- Tests/BONFontBehaviorTests.swift
- Tests/ComposableTests.swift
- Tests/EmphasisTests.swift
- Tests/FontInspectorTests.swift
- Tests/ImageTintingTests.swift
- Tests/NSAttributedStringDebugTests.swift
- Tests/TextAlignmentConstraintTests.swift
- Tests/TransformTests.swift
- Tests/UIKitBonMotTests.swift
- Tests/XMLTagStyleBuilderTests.swift
- scripts/iOS-12.1.sh
- scripts/tvOS-12.1.sh
- scripts/watchOS-5.1.sh
The hardcoded SwiftLint version was causing issues with running [muter](https://github.com/SeanROlszewski/muter) for mutation testing. Also took the opportunity to add some additional SwiftLint rules and make sure the AllTheThings target is working.
> Linting updates

- .circleci/config.yml
- BonMot.podspec
- Gemfile
- Gemfile.lock
* Uses CocoaPods 1.7.0rc2 for Swift 4.2 + 5.0 podspec support
* CocoaPods 1.7 Specs CDN
* Use CircleCI 2.1 executors and commands
> Cleanup CircleCI

- Sources/StringStyle+Part.swift
- Sources/StringStyle.swift
- Tests/AssertHelpers.swift
- Tests/AttributedStringStyleTests.swift
- Tests/ComposableTests.swift
- Tests/Helpers.swift
Hi, would you consider merging this please.
> Add allowsDefaultTighteningForTruncation paragraph attribute

- BonMot.podspec
- Sources/UIKit/AdaptableTextContainer.swift
- Tests/UIKitBonMotTests.swift
Fixes merge conflicts for #398
> Fixed merge conflicts for PR #398

- Sources/StringStyle+Part.swift
- Sources/StringStyle.swift
- Tests/AttributedStringStyleTests.swift
- Tests/ComposableTests.swift
Add lineBreakStrategy paragraph attribute
> Add lineBreakStrategy paragraph attribute
